import type { Metadata } from "next";
import {  Titillium_Web } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar";


const titillium = Titillium_Web({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'], // Include all weights you need
  variable: '--font-titillium', // CSS variable name
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${titillium.variable}`}>
      <body
       className="font-sans"
      >
        
          <NavBar />
              <main className="">

          {children}
          
          </main>
      </body>
    </html>
  );
}
